print()
c = int(input("How many rooms (classrooms + offices)? "))
w = int(input("How many water fountains? "))
wl = input("Where are the water fountains?")
r = int(input("How many restrooms? "))
rl = input("Where are the restrooms?")
g = int(input("How many gyms? "))
gl = input("Where are the gyms?")
ca = int(input("How many common areas? "))
cal = input("Where are the common areas? ")

print()
print("1. Water Fountains:")
print(f"    - There are {w} water fountains.")
print(f"    - There are {round(w/c,2)} water fountains per room")
print(f"Water Fountain Location: {wl}")

print()
print("2. Restrooms:")
print(f"    - There are {r} restrooms.")
print(f"    - There are {round(r/c,2)} restrooms per room")
print(f"Restrooms Location: {rl}")

print()
print("3. Gyms:")
print(f"    - There are {g} gyms.")
print(f"    - There are {round(g/c,2)} gyms per room")
print(f"Gyms Location: {gl}")

print()
print("4. Common Areas:")
print(f"    - There are {ca} common areas.")
print(f"    - There are {round(ca/c,2)} common areas per room")
print(f"Common areas location: {cal}")
print()